### ISSUE TITLE
Crate does not build on Ubuntu 18.04

### ISSUE THREAD

**Issue by loganwendholt** [wangbj/syscalls#2]
Running `cargo build` on my Ubuntu 18.04 box results in the following error:

```
   Compiling syscalls v0.1.0 (/home/logan/cloudseal/syscalls)
error: failed to run custom build command for `syscalls v0.1.0 (/home/logan/cloudseal/syscalls)`

Caused by:
  process didn't exit successfully: `/home/logan/cloudseal/syscalls/target/debug/build/syscalls-0e6f2ed3f9466713/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `335`,
 right: `424`: generated syscalls are not sequential', build.rs:101:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: build_script_build::gen_syscall_nrs
             at ./build.rs:101
  10: build_script_build::main
             at ./build.rs:155
  11: std::rt::lang_start::{{closure}}
             at /rustc/9b91b9c10e3c87ed333a1e34c4f46ed68f1eee06/src/libstd/rt.rs:64
  12: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  13: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  15: std::panicking::try
             at src/libstd/panicking.rs:275
  16: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  17: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  18: std::rt::lang_start
             at /rustc/9b91b9c10e3c87ed333a1e34c4f46ed68f1eee06/src/libstd/rt.rs:64
  19: main
  20: __libc_start_main
  21: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by loganwendholt** [comment]
@wangbj @jasonwhite any thoughts on what's going on here?

**Comment by loganwendholt** [comment]
I took a look at my copy of `unistd_64.h`, and it does indeed skip some numbers right at the end:
```
$ tail -n 20 /usr/include/asm/unistd_64.h 
#define __NR_pkey_mprotect 329
#define __NR_pkey_alloc 330
#define __NR_pkey_free 331
#define __NR_statx 332
#define __NR_io_pgetevents 333
#define __NR_rseq 334
#define __NR_pidfd_send_signal 424
#define __NR_io_uring_setup 425
#define __NR_io_uring_enter 426
#define __NR_io_uring_register 427
#define __NR_open_tree 428
#define __NR_move_mount 429
#define __NR_fsopen 430
#define __NR_fsconfig 431
#define __NR_fsmount 432
#define __NR_fspick 433
#define __NR_pidfd_open 434
#define __NR_clone3 435

#endif /* _ASM_X86_UNISTD_64_H */
```

Is there any reason why we need an assert on this? Does the hop from 334 to 424 cause problems?

**Comment by jasonwhite** [comment]
Thanks for the PR. I published a new version.
